MDI content transitions
nightingaleproject/vital_records_sandbox_ig pull request #33
Opened 2023-08-15 17:51 UTC by rpassas

## Summary

Added MDI content transitioning or worth highlighting from our harmonization proposal. 

Omitted: bundles, compositions, messages

2023-08-15 18:08 UTC, saulakravitz requested changes

2023-08-15 18:08 UTC, saulakravitz commented on input/pagecontent/mdi-content-transitions.md
> +{: .grid }
Include the medical-history section, with reference to USCore Conditions.

2023-08-15 18:08 UTC, saulakravitz commented on input/pagecontent/mdi-content-transitions.md
> +|Autopsy Performed Indicator | MDI Profiles  |    -    | [ObservationAutopsyPerformedIndicator] |    -    |   -   |
Add autopsy location with reference to USCoreLocation.  We will probably add a location profile for this to make it easier to query, just like we did for death location, injury location, and disposition location.

2023-08-15 18:08 UTC, saulakravitz commented on input/pagecontent/mdi-content-transitions.md
> +|Cause of Death Part 1 |  MDI Profiles  |  -  | [ObservationCauseOfDeathPart1] | [ObservationCauseOfDeathPart1VitalRecordsNew] |   -   |
Add Decedent, with reference to USCorePatient.   (subject field)
Add Medical Examiner/Coroner (Certifier), with reference to USCorePractitioner (attester field).

2023-08-15 21:24 UTC, rpassas commented on input/pagecontent/mdi-content-transitions.md
> +# MDI to EDRS
This was included, but I added "performer" as well.

2023-08-16 21:35 UTC, saulakravitz approved these changes

2023-08-16 21:35 UTC, merged