New composition bfdr
nightingaleproject/vital_records_sandbox_ig pull request #37
Opened 2023-09-01 17:58 UTC by rpassas

### Summary

Pulled in updated BFDR repository profiles/examples, created examples for compositions and migrated profiles, and resolved errors created by the profile/example changes.

Per our conversations the following were relatively untouched: inline examples (and bundles as a result), race/ethnicity composition.

Other items: 
- **plurality** It's included as an edit flag in jurisdiction compositions and is still referenced in inline examples. It was replaced by numberLiveBirthsThisDelivery + numberFetalDeathsThisDelivery
- the profiles that moved to BFDR from VRCL need examples with URLs in their meta.profile

2023-09-18 22:23 UTC, saulakravitz requested changes

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/bundlescompositions/BundleDocumentBFDRNew.fsh
> +* ^meta.source = "#9Kkc7086j0eYQVSm"
Delete this trifolia detritus wherever found.

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/bundlescompositions/BundleDocumentBFDRNew.fsh
> +* ^publisher = "HL7 Public Health Work Group"
Delete ^publisher wherever found.

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/bundlescompositions/CompositionCodedCauseOfFetalDeathNew.fsh
> +* ^jurisdiction = urn:iso:std:iso:3166#US "United States of America"
Delete wherever found.

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/bundlescompositions/CompositionJurisdictionFetalDeathReportNew.fsh
> +    * ^slicing.discriminator.type = #profile
Make/find a ruleset for profile-based-open-slicing and replace everywhere.

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/bundlescompositions/CompositionJurisdictionFetalDeathReportNew.fsh
> +    * ^slicing.rules = #open
This should also include unordered (probably the default), so can use the to-be-found/defined ruleset

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/bundlescompositions/CompositionJurisdictionLiveBirthReportNew.fsh
> +* ^jurisdiction = urn:iso:std:iso:3166#US "United States of America"
delete

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/bundlescompositions/CompositionJurisdictionLiveBirthReportNew.fsh
> +  * ^slicing.rules = #open
I think this is the default for extension slices.  Can probably be deleted everywhere.

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/bundlescompositions/CompositionJurisdictionLiveBirthReportNew.fsh
> +    * ^short = "Entries that are contained in the Mother Prenatal section"
profile-based open slicing, unordered --> ruleset.

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/bundlescompositions/CompositionProviderFetalDeathReportNew.fsh
> +* ^jurisdiction = urn:iso:std:iso:3166#US "United States of America"
delete

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/bundlescompositions/CompositionProviderFetalDeathReportNew.fsh
> +  * ^slicing.rules = #open
I think this is the default for composition sections.   May be able to delete this.   Everywhere there are composition sections.

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/instances/Inline-Instance-for-bundle-jurisdiction-fetal-death-not-named-10.fsh
I thought we were going to get rid of all of the inline instances, a la VRDR.
They aren't shown as examples of individual profiles, which is a shame.
All of the examples I looked at look they been repurposed from one type of observation to another which makes me scratch my head.

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/instances/Inline-Instance-for-bundle-jurisdiction-fetal-death-not-named-16.fsh
THis doesn't look right.   Switching out smoking for education....

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/instances/Inline-Instance-for-bundle-jurisdiction-fetal-death-not-named-14.fsh
THis doesn't look right... Switching out plurality for WIC

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/instances/Inline-Instance-for-bundle-jurisdiction-fetal-death-not-named-13.fsh
THis doesn't look right.  Switching out normal delivery finding for prepregnancy weight.

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/migratingInstances/observation-apgar-score-babyg-quinn-1-min-new.fsh
> +  * lastUpdated = "2023-04-06T00:25:56.510Z"
delete -- in all instances.

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/valuesets/ReplaceStatus.fsh
> +* ^status = #active
delete

2023-09-18 22:23 UTC, saulakravitz commented on input/fsh/BFDR/valuesets/ReplaceStatus.fsh
> +* ^publisher = "HL7 International - Public Health Work Group"
delete

2023-09-19 20:10 UTC, ptran265 commented on input/fsh/BFDR/bundlescompositions/BundleDocumentBFDRNew.fsh
> +* entry[BFDRComposition].resource only Composition
Not sure if generalization is intentional here, but the original bundle references the 4 specific compositions: 

* resource only CompositionProviderLiveBirthReport or CompositionProviderFetalDeathReport or CompositionJurisdictionLiveBirthReport or CompositionJurisdictionFetalDeathReport

2023-09-20 02:58 UTC, rpassas commented on input/fsh/BFDR/bundlescompositions/CompositionProviderLiveBirthReportNew.fsh
> +  * entry[pregnancyRiskFactors] only Reference(Condition-prepregnancy-diabetes-vr or Condition-gestational-diabetes-vr or Condition-prepregnancy-hypertension-vr or Condition-gestational-hypertension-
I assume you mean reference by ID, not profile. I think this was a goFSH conversion - changing it to profile references.

2023-09-20 15:30 UTC, saulakravitz approved these changes
Let's merge and move forward.

2023-09-20 17:05 UTC, merged