financial class VS and CS
nightingaleproject/vital_records_sandbox_ig pull request #5
Opened 2023-06-30 04:23 UTC by rpassas

## Changes 
Added Code System and Value System for "BirthAndFetalDeathFinancialClass"

**note:** did not include concept map because of IJE - VS mismatch. All values matched except IJE had an "other" while PHINVADS included no other but a "No Typology Code available for payment source" which IJE lacked. A concept map was created with the matching one codes but not included (based on email exchange on 1-1 mappings needed).

2023-06-30 16:02 UTC, saulakravitz commented
See https://jira.mitre.org/browse/NVSSIG-14

For now, please build concept map using other <-->no typology code.
We will probably revisit this valueset once we are in control of BFDR, but let's provide the best guess mapping for now.

2023-06-30 16:12 UTC, saulakravitz requested changes
Add Concept Map....

2023-06-30 16:50 UTC, rpassas commented
> 

I made that change prior to seeing your comment. Added back the concept map

2023-07-03 14:10 UTC, saulakravitz approved these changes

2023-07-03 15:21 UTC, merged